export const LOGGER_RECOGNITION_EVENT_TYPES: readonly [
  'CORE_WEIGHT_PR',
  'CORE_REP_MAX_PR',
  'CORE_RPE_PR',
  'CORE_SAME_WEIGHT_REP_PR',
  'CORE_E1RM_PR',
  'CORE_BLOCK_WEIGHT_BEST',
  'CORE_BLOCK_REP_MAX_BEST',
  'CORE_BLOCK_SAME_WEIGHT_REP_BEST',
  'CORE_BLOCK_E1RM_BEST',
  'CORE_PRESCRIPTION_COMPLETED',
  'CORE_MOVEMENT_SESSION_COMPLETED',
  'CORE_LIFETIME_VOLUME_MILESTONE',
  'TOTAL_LIFETIME_VOLUME_MILESTONE',
];

export type LoggerRecognitionEventType = typeof LOGGER_RECOGNITION_EVENT_TYPES[number];
