// Generated by scripts/pack-volume-medallions.py; exact original RGBA pixels.
import type { MajorVolumeMedallionImageSource } from './major-volume-medallion-assets';
import type { MajorVolumeMedallionFamily } from './major-volume-milestones';
const atlas0 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-01.png');
const atlas1 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-02.png');
const atlas2 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-03.png');
const atlas3 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-04.png');
const atlas4 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-05.png');
const atlas5 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-06.png');
const atlas6 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-07.png');
const atlas7 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-08.png');
const atlas8 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-09.png');
const atlas9 = require('@/assets/images/major-volume-medallions/kg-atlases/kg-10.png');
export const MAJOR_VOLUME_MEDALLION_KG_ASSETS: Record<MajorVolumeMedallionFamily, Record<number, MajorVolumeMedallionImageSource>> = {
  total: {
    100000: { source: atlas0, columns: 2, rows: 2, column: 0, row: 0 },
    250000: { source: atlas0, columns: 2, rows: 2, column: 1, row: 0 },
    500000: { source: atlas0, columns: 2, rows: 2, column: 0, row: 1 },
    1000000: { source: atlas0, columns: 2, rows: 2, column: 1, row: 1 },
    2000000: { source: atlas1, columns: 2, rows: 2, column: 0, row: 0 },
    5000000: { source: atlas1, columns: 2, rows: 2, column: 1, row: 0 },
    10000000: { source: atlas1, columns: 2, rows: 2, column: 0, row: 1 },
    25000000: { source: atlas1, columns: 2, rows: 2, column: 1, row: 1 },
    50000000: { source: atlas2, columns: 2, rows: 2, column: 0, row: 0 },
    75000000: { source: atlas2, columns: 2, rows: 2, column: 1, row: 0 },
    100000000: { source: atlas2, columns: 2, rows: 2, column: 0, row: 1 },
    150000000: { source: atlas2, columns: 2, rows: 2, column: 1, row: 1 },
    250000000: { source: atlas3, columns: 2, rows: 2, column: 0, row: 0 },
    500000000: { source: atlas3, columns: 2, rows: 2, column: 1, row: 0 },
    750000000: { source: atlas3, columns: 2, rows: 2, column: 0, row: 1 },
    1000000000: { source: atlas3, columns: 2, rows: 2, column: 1, row: 1 },
  },
  squat: {
    100000: { source: atlas4, columns: 2, rows: 2, column: 0, row: 0 },
    250000: { source: atlas4, columns: 2, rows: 2, column: 1, row: 0 },
    500000: { source: atlas4, columns: 2, rows: 2, column: 0, row: 1 },
    1000000: { source: atlas4, columns: 2, rows: 2, column: 1, row: 1 },
    2000000: { source: atlas5, columns: 2, rows: 2, column: 0, row: 0 },
    5000000: { source: atlas5, columns: 2, rows: 2, column: 1, row: 0 },
    10000000: { source: atlas5, columns: 2, rows: 2, column: 0, row: 1 },
  },
  bench: {
    100000: { source: atlas5, columns: 2, rows: 2, column: 1, row: 1 },
    250000: { source: atlas6, columns: 2, rows: 2, column: 0, row: 0 },
    500000: { source: atlas6, columns: 2, rows: 2, column: 1, row: 0 },
    1000000: { source: atlas6, columns: 2, rows: 2, column: 0, row: 1 },
    2000000: { source: atlas6, columns: 2, rows: 2, column: 1, row: 1 },
    5000000: { source: atlas7, columns: 2, rows: 2, column: 0, row: 0 },
    10000000: { source: atlas7, columns: 2, rows: 2, column: 1, row: 0 },
  },
  deadlift: {
    100000: { source: atlas7, columns: 2, rows: 2, column: 0, row: 1 },
    250000: { source: atlas7, columns: 2, rows: 2, column: 1, row: 1 },
    500000: { source: atlas8, columns: 2, rows: 2, column: 0, row: 0 },
    1000000: { source: atlas8, columns: 2, rows: 2, column: 1, row: 0 },
    2000000: { source: atlas8, columns: 2, rows: 2, column: 0, row: 1 },
    5000000: { source: atlas8, columns: 2, rows: 2, column: 1, row: 1 },
    10000000: { source: atlas9, columns: 1, rows: 1, column: 0, row: 0 },
  },
};
