"""Losslessly package existing KG PNG pixels; never generate or alter artwork."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'assets/images/major-volume-medallions'
OUT = ART / 'kg-atlases'
OUT.mkdir(exist_ok=True)
markers = [('100k', 100000), ('250k', 250000), ('500k', 500000),
           ('1m', 1000000), ('2m', 2000000), ('5m', 5000000), ('10m', 10000000)]
extended = [('25m', 25000000), ('50m', 50000000), ('75m', 75000000),
            ('100m', 100000000), ('150m', 150000000), ('250m', 250000000),
            ('500m', 500000000), ('750m', 750000000), ('1b', 1000000000)]
entries = [(family, marker, value) for family in ('total', 'squat', 'bench', 'deadlift')
           for marker, value in markers + (extended if family == 'total' else [])]
digest = lambda file: hashlib.sha256(file.read_bytes()).hexdigest()
records = []
assets = []
for start in range(0, len(entries), 4):
    group = entries[start:start + 4]
    columns = min(2, len(group))
    rows = (len(group) + columns - 1) // columns
    tile_size = 1254
    atlas = Image.new('RGBA', (columns * tile_size, rows * tile_size))
    file = OUT / f'kg-{start // 4 + 1:02}.png'
    originals = []
    for index, (family, marker, value) in enumerate(group):
        original = ART / f'kg/{family}/{family}-{marker}-kg.png'
        source = Image.open(original)
        assert source.mode == 'RGBA' and source.size == (tile_size, tile_size)
        column, row = index % columns, index // columns
        atlas.paste(source, (column * tile_size, row * tile_size))
        originals.append((source, column, row))
        records.append(dict(family=family, marker=value, original=str(original.relative_to(ROOT)),
                            originalSha256=digest(original), atlas=str(file.relative_to(ROOT)),
                            columns=columns, rows=rows, column=column, row=row))
    atlas.save(file)
    decoded = Image.open(file)
    for original, column, row in originals:
        recovered = decoded.crop((column * tile_size, row * tile_size,
                                  (column + 1) * tile_size, (row + 1) * tile_size))
        assert recovered.tobytes() == original.tobytes(), 'Packing must preserve every RGBA pixel'
    assets.append(dict(path=str(file.relative_to(ROOT)), sha256=digest(file),
                       width=atlas.width, height=atlas.height))
(OUT / 'manifest.json').write_text(json.dumps(dict(assets=assets, entries=records), indent=2) + '\n')
lines = ["// Generated by scripts/pack-volume-medallions.py; exact original RGBA pixels.",
         "import type { MajorVolumeMedallionImageSource } from './major-volume-medallion-assets';",
         "import type { MajorVolumeMedallionFamily } from './major-volume-milestones';"]
for index, asset in enumerate(assets):
    lines.append(f"const atlas{index} = require('@/{asset['path']}');")
lines.append('export const MAJOR_VOLUME_MEDALLION_KG_ASSETS: Record<MajorVolumeMedallionFamily, Record<number, MajorVolumeMedallionImageSource>> = {')
for family in ('total', 'squat', 'bench', 'deadlift'):
    lines.append(f'  {family}: {{')
    for index, entry in enumerate(records):
        if entry['family'] != family:
            continue
        lines.append(f"    {entry['marker']}: {{ source: atlas{index // 4}, columns: {entry['columns']}, rows: {entry['rows']}, column: {entry['column']}, row: {entry['row']} }},")
    lines.append('  },')
lines.append('};')
(ROOT / 'lib/major-volume-medallion-kg-atlases.ts').write_text('\n'.join(lines) + '\n')
print(f'Packed {len(records)} unchanged images into {len(assets)} assets; every recovered RGBA pixel matches.')
